### ISSUE TITLE
可以继承美团热修复框架Robust么

### ISSUE THREAD

**Issue by mm46468648** [aa5279aa/android_all_demo#1]
如题：
因为最新的gradle7.1.2的语法不兼容，你有什么解决的办法么

**Comment by aa5279aa** [comment]
这是两码事。
1.美团热修框架和我这个项目没有什么关系，我这个只是一个各种技术的尝鲜项目。
2.项目gradle升级到7.1.2并不是什么问题，只是目前对我来说没有升级的必要。
